language: elixir
elixir:
  - 1.4.2
otp_release:
  - 19.0

language: node_js
node_js:
  - "6.10.0"
script: npm --prefix ./assets test
# before_install:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
before_script:
  - npm --prefix ./assets install
