matrix:
  include:
    - language: elixir
      elixir:
        - 1.4.2
      otp_release:
        - 19.0
    - language: node_js
      node_js:
        - "6.10.0"
      script: npm test
      before_deploy:
        - cd assets
      # before_install:
      #   - export DISPLAY=:99.0
      #   - sh -e /etc/init.d/xvfb start
      before_script:
        - cd assets
        - npm install
